version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:cached
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      HOME: /app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    links:
      - db

volumes:
  bundle:
    driver: local
  data:
    driver: local
